// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlayerSyncInterface.Database;

#nullable disable

namespace MusicPlayerDXMonoGamePort.Migrations
{
    [DbContext(typeof(SongDbContext))]
    [Migration("20260514192239_AddForeignKeyToSongHistoryEntry")]
    partial class AddForeignKeyToSongHistoryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Persistence.Database.SongHistoryEntry", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SongName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float>("ScoreChange")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("SongId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "SongName", "Date");

                    b.HasIndex("SongId");

                    b.ToTable("SongHistoryEntries");
                });

            modelBuilder.Entity("Persistence.Database.UpvotedSong", b =>
                {
                    b.Property<Guid>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AddingDates")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Streak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDislikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("SongId");

                    b.HasIndex("UserId", "Name", "Artist", "Album")
                        .IsUnique();

                    b.ToTable("UpvotedSongs");
                });

            modelBuilder.Entity("Persistence.Database.SongHistoryEntry", b =>
                {
                    b.HasOne("Persistence.Database.UpvotedSong", "UpvotedSong")
                        .WithMany()
                        .HasForeignKey("SongId");

                    b.Navigation("UpvotedSong");
                });
#pragma warning restore 612, 618
        }
    }
}
