// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlayerSyncInterface.Database;

#nullable disable

namespace MusicPlayerDXMonoGamePort.Migrations
{
    [DbContext(typeof(SongDbContext))]
    [Migration("20260507143231_ExtendUpvotedSongKey")]
    partial class ExtendUpvotedSongKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Persistence.Database.UpvotedSong", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT");

                    b.Property<long>("AddingDates")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Streak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDislikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Name", "Artist", "Album");

                    b.ToTable("UpvotedSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
